apiVersion: v1
kind: Service
metadata:
  name: ochestrator-service
  namespace: kafka
spec:
  selector:
    app: ochestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5015  
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ochestrator
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ochestrator
  template:
    metadata:
      labels:
        app: ochestrator
    spec:
      containers:
        - name: ochestrator
          image: wubbles1012/flask-ochestrator:0.0.3 
          ports:
            - containerPort: 5015
